version: 2.1

jobs:
  print_myname:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say my name"
          command: "echo $MY_NAME"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-myname:
    jobs:
      - print_myname
