version: 2.1

commands: 
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  print_workflow_id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  echo-workflow-id:
    jobs:
      - print_workflow_id
