version: 2.1

commands: 
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: |
          echo << parameters.id >>
          return 1

jobs:
  print_workflow_id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
      - run:
          name: Upload Failed Tests
          command: echo "Hello Error!"
          when: on_fail

workflows:
  echo-workflow-id:
    jobs:
      - print_workflow_id
