version: 2.1

commands: 
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

jobs:
  print_workflow_id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          id: << CIRCLE_WORKFLOW_ID >>

workflows:
  echo-workflow-id:
    jobs:
      - print_workflow_id
